USE [SubstitutionDb]
GO
CREATE TABLE [dbo].[lookupAddresstable](
	[AddressID] [int] NULL,
	[placeName] [nvarchar](max) NULL)
GO
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (1, N'SEB Merchant Banking, Filipstad Brygge 1, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (2, N'yA Bank, Langkaia 1, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (3, N'SpareBank 1 Gruppen AS, Hammersborggata 2, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (4, N'Bank2 ASA, Henrik Ibsens gate 60B, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (5, N'Netfonds Bank AS, Stenersgata 2, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (6, N'BN Bank avdeling for Næringseiendom, Tordenskiolds gate 8, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (7, N'SpareBank 1 Østlandet, Youngstorget 5, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (8, N'DAHABSHIIL OSLO, Storgata 43, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (9, N'Eksportkreditt Norge, Cort Adelers gate 30, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (10, N'Axo Finance, Fridtjof Nansens plass 7, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (11, N'Finansa AS, Storgata 10B, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (12, N'JP Morgan Europe Limited, Tordenskiolds gate 6, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (13, N'RørosBanken, Par[dbo].[lookupAddresstable]kveien 53B, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (14, N'KLP Banken, Dronning Eufemias gate 10, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (15, N'Eurocard, Filipstad Brygge 1, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (16, N'SEB Kort Bank AB Oslofilialen, Filipstad Brygge 1, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (17, N'Crédit Agricole Cib Representative office Norway, Ruseløkkveien 6, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (18, N'Minibank, Torggata 9-11, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (19, N'BlueStep Bank AB (publ), branch Oslo, Skippergata 31, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (20, N'Gjensidige Bank, Schweigaards gate 14, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (21, N'Aleris sykehus og medisinske senter i Oslo, Frederik Stangs gate 11-13, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (22, N'Oslo City Legesenter, Stenersgata 1, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (23, N'Oslo University Hospital, Sognsvannsveien 20, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (24, N'Diakonhjemmet Hospital, Diakonveien 12, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (25, N'ABC All Bright & Clear Synskirurgi AS, Storgata 23, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (26, N'Balderklinikken AS, Munchs gate 7, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (27, N'KAL clinic, Sognsveien 75F, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (28, N'Lovisenberg Diakonale Sykehus AS, Lovisenberggata 17, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (29, N'Lovisenberg Diakonale Sykehus Psykiatrisk Avdeling, Ekebergveien 1, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (30, N'Volvat Medisinske Senter | Oslo | Majorstuen, Borgenveien 2A, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (31, N'Oslo Medical Center AS - Legesenter Oslo, 0184, Storgata 40, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (32, N'Enerhaugen Medical Center, Klinikk Barcode, Wismargata 2, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (33, N'Vital Legekontor, Grønlandsleiret 31, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (34, N'Ringvoll Klinikken avd Oslo, Pilestredet Park 7, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (35, N'Volvat Medisinske Senter | Oslo | Nationaltheatret, Stortingsgata 30, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (36, N'Oslo Hospital, Ekebergveien 1, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (37, N'Lovisenberg DPS - Ekebergveien, Ekebergveien 1, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (38, N'Stamina Helse Bryggeklinikken, Munkedamsveien 45, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (39, N'Aker Brygge Legesenter, Stranden 89, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (40, N'Norwegian Medical Offices, Hegdehaugsveien 31, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (41, N'SpareBank 1 Lom og Skjåk avd. Lom, Sognefjellsvegen 4')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (42, N'Nationaltheatret stasjon, Ruseløkkveien 1, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (43, N'Oslo Central Station, Jernbanetorget 1, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (44, N'Oslo bussterminal, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (45, N'Oslo, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (46, N'Hammersborggata, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (47, N'Jernbanetorget, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (48, N'Hammersborggata, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (49, N'Jernbanetorget, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (50, N'Oslo Bussterminal, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (51, N'Jernbanetorget, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (52, N'Bussterminalen Grønland, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (53, N'Oslo bussterminal, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (54, N'Tollboden, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (55, N'Oslo bussterminal, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (56, N'Oslo bussterminal, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (57, N'Oslo bussterminal, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (58, N'St. Olavs plass, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (59, N'Holbergs plass, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (60, N'Vippetangen ferjeterminal, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (61, N'Oslo Hospital, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (62, N'Statens Lånekasse for utdanning, Bradbenken 1, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (63, N'Sparebanken Sogn og Fjordane, Christian Michelsens gate 4, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (64, N'Indre Sogn sparebank, Valkendorfsgaten 2B, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (65, N'Santander Consumer Bank AS, Sjøgaten 66, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (66, N'Eiendomskreditt AS, Solheimsgaten 11, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (67, N'BRAbank, Starvhusgaten 4, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (68, N'DNB, Torgallmenningen 2, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (69, N'Handelsbanken Bergen Sentrum, Allehelgens gate 4, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (70, N'Fana Savings Bank City Office, Kaigaten 8, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (71, N'Jbf - Jernbanepersonalets Bank og forsikring, Strandgaten 53, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (72, N'Sbanken ASA, Folke Bernadottes vei 38, Fyllingsdalen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (73, N'Handelsbanken Minde, Conrad Mohrs veg 11, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (74, N'Handelsbanken Fyllingsdalen Bergen, Folke Bernadottes vei 38, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (75, N'Danske Bank Bergen, Christian Michelsens gate 6B, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (76, N'Starvhusgaten 2 A AS, Torgallmenningen 12, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (77, N'Jernbanepersonalets Bank og forsikring, Lungegårdsbakken 1, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (78, N'SpareBank 1 SR-Bank, Krinkelkroken 1, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (79, N'Nordea, Allehelgens gate 2, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (80, N'Sparebanken Vest, Minibank, Markeveien 1C, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (81, N'Danske Bank Selvbetjeningscenter, Christian Michelsens gate 6 B, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (82, N'Lom helsesenter, Sekundær Fylkesveg 467 184, Lom')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (83, N'Nationaltheatret stasjon, Ruseløkkveien 1, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (84, N'Oslo Central Station, Jernbanetorget 1, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (85, N'Tøyen stasjon, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (86, N'Bryn, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (87, N'Økern, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (88, N'Grefsen stasjon, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (89, N'Skøyen stasjon, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (90, N'Nydalen stasjon, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (91, N'Psychiatric Clinic, Haukeland University Hospital, Sandviksleitet 1, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (92, N'Privatklinikken Bergen, Nattlandsveien 8, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (93, N'Haukeland University Hospital / Health Bergen, Jonas Lies vei 65, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (94, N'Legekontoret for sjømenn, Bergen Bedriftshelsetjeneste og Private Legekontor ASAS, Strandgaten 18, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (95, N'B-sykehuset, Solhaugveien 15, Laksevåg')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (96, N'Rafto klinikken Legekontor, Magnus Barfots gate 20, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (97, N'Bergen Vene Center, Xhibition Shopping Center, Småstrandgaten 3, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (98, N'Nygårdsgaten Legesenter DA, Nygårdsgaten 4, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (99, N'Helse Bergen, Avdeling for rusmedisin, Ekspedisjon i 4. etasje, Østre Murallmenningen 7, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (100, N'Clear Ink, Marken 32, Bergen')
GO
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (101, N'Lege Bergen - Aleris Medisinske Senter, Marken 34, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (102, N'Dokumentasjonsavdelingen, Haukeland universitetssjukehus, Møllendalsbakken 7, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (103, N'Øyebygget, Jonas Lies vei 72C, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (104, N'Augeavdelinga, Poliklinikk, Haukeland univeristetssjukehus, Jonas Lies vei 72, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (105, N'Lytteposten - Helse Bergen, Jonas Lies vei 65, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (106, N'Volvat Medisinske Senter | Bergen | Ulriksdal, Ulriksdal 2, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (107, N'Kirurgisk poliklinikk, Haraldsplass Diakonale Sykehus, Ulriksdal 8, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (108, N'Senter for søvnmedisin, Jonas Lies vei 65, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (109, N'Busp Haukeland, Haukelandsbakken 16C, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (110, N'Children and Youth Hospital of Bergen, Haukelandsbakken 15, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (111, N'Lom, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (112, N'Jernbanepersonalets bank og forsikring avdeling Trondheim, Søndre gate 16, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (113, N'365 Direct, 15, Søndre gate 13, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (114, N'Nordea, Kongens gate 18, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (115, N'FOREX Bank, Munkegata 34, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (116, N'SpareBank 1 Finans Central Norway AS, Søndre gate 4, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (117, N'SpareBank 1, Søndre gate 4, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (118, N'SpareBank 1 Smn, Dronningens gate 10, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (119, N'Handelsbanken, Søndre gate 14, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (120, N'Dahabshiil money transfer, Kjøpmannsgata 41, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (121, N'DNB Næringsmegling AS, Beddingen 16, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (122, N'Danske Bank Solsiden, Beddingen 2, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (123, N'SpareBank 1 SMN, Brøsetvegen 164, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (124, N'Orkla Sparebank avd Trondheim, Jonsvannsveien 140, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (125, N'Handelsbanken Trondheim Leangen, Falkenborgvegen 9, Leangen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (126, N'Surnadal Sparebank, Olav Tryggvasons Gate 1, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (127, N'Danske Bank Trondheim, Søndre gate 13-15, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (128, N'Danske Bank Nordregate, Nordre gate 12, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (129, N'DNB, Munkegata 22, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (130, N'Selbu Sparebank, Søndre gate 16, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (131, N'SpareBank 1 SMN Trondheim, Valentinlyst, Brøsetvegen 164, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (132, N'The Thief, Landgangen 1, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (133, N'Clarion Collection Hotel Gabelshus, Gabels gate 16, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (134, N'Grand Hotel Oslo, Karl Johans gate 31, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (135, N'Scandic Sjølyst, Sjølyst plass 5, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (136, N'Hotell Bondeheimen, Rosenkrantz'' gate 8, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (137, N'Scandic Vulkan, Vulkan, Maridalsveien 13A, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (138, N'Hotel Continental, Oslo, Stortingsgata 24/26, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (139, N'First Hotel Grims Grenka, Kongens gate 5, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (140, N'Quality Hotel 33, Østre Aker vei 33, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (141, N'Scandic, St. Olavs plass 1, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (142, N'Brasserie France, Øvre Slottsgate 16, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (143, N'Hard Rock Cafe, Karl Johans gate 45, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (144, N'Delicatessen Grünerløkka, Søndre gate 8, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (145, N'Engebret Cafe, Bankplassen 1, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (146, N'Dinner Restaurant, Stortingsgata 22, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (147, N'Lofoten Fiskerestaurant, Stranden 75, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (148, N'Baltazar Ristorante & Enoteca, Dronningens gate 27, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (149, N'Stortorvets Gjæstgiveri, Grensen 1, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (150, N'The Great India Restaurant, Kristian Augusts gate 14, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (151, N'Mathallen Oslo, Vulkan 5, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (152, N'Nordea, Bragernes Torg 1, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (153, N'Danske Bank Drammen, Hauges gate 3-5, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (154, N'Jernbanepersonalets bank og forsikring avdeling Drammen, Torgeir Vraas plass 5, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (155, N'Handelsbanken Drammen, Bragernes Torg 4 A, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (156, N'Toyota Kreditbank GmbH, Svelvikveien 59, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (157, N'Sparebanken Øst Drammen (Konnerud), Pettersvollen 3, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (158, N'SpareBank 1 BV, Hauges gate 2, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (159, N'Sparebanken Øst Drammen, Bragernes, Bragernes Torg 2, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (160, N'Sparebanken Øst Drammen (Gulskogen), Professor Smiths alle 56, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (161, N'DNB Drammen, Bragernes Torg 11, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (162, N'Skue Sparebank avd Drammen, Bragernes Torg 1A, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (163, N'Ria Moneytransfer, Tollbugata 12, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (164, N'Øya helsehus, Mauritz Hansens gate 2, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (165, N'Sirkulasjonsklinikken, Prinsens Gate 19, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (166, N'St. Olav''s University Hospital, Prinsesse Kristinas gate 3, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (167, N'Trondheim Heart Center AS, Havnegata 7, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (168, N'Nevrosenteret, Harald Hardrådes gate 5, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (169, N'Nasjonalt Senter for Fostermedisin, Olav Kyrres gate 11, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (170, N'Gastrosenteret, Prinsesse Kristinas gate 1, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (171, N'SIFER Midt, St.Olavs Hospital, Brøsetvegen 100, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (172, N'Bevegelsessenteret, Olav Kyrres gate 13, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (173, N'Munkholmen Medical Offices, Fjordgata 82, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (174, N'St. Olavs hospital HF - Klinikk rus og avhengighetsbehandling, Klostergata 46, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (175, N'Kunnskapssenteret, Olav Kyrres gate 17, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (176, N'PET-senteret St. Olav hospital, Ragnhilds gate 16A, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (177, N'1930-bygget, Harald Hardrådes gate 12, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (178, N'Akutten og Hjerte-lunge-senteret, Prinsesse Kristinas gate 3, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (179, N'Forsyningssenteret, Prinsesse Kristinas gate 5, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (180, N'LHL-klinikken Trondheim, Jarleveien 12, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (181, N'Nidaros DPS, Østmarkveien 21, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (182, N'Aleris Røntgen Trondheim, Innherredsveien 7D (inngang fra, Kirkegata, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (183, N'St. Olavs Hospital HF, Olav Kyrres gate 17, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (184, N'Bergen stasjon, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (185, N'Bergen busstasjon, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (186, N'Platekompaniet, Jernbanetorget 6, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (187, N'Tanum Oslo City, Stenersgata 1, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (188, N'Paleet, Karl Johans gate 37 - 43, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (189, N'Akademika Blindern, 0314, Problemveien 9, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (190, N'Mystic Dreamer Torunn Riise Larsen, Briskebyveien 38, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (191, N'Platekompaniet - Storo, Storo Storsenter, Vitaminveien 7-9, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (192, N'Akademika Nydalen, Handelshøyskolen BI, Sandakerveien 118, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (193, N'ARK Sandaker Oslo, Sandakerveien 59, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (194, N'Damms Antikvariat AS, Frederik Stangs gate 41, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (195, N'Fri bookstore SA, Sehesteds gate 6, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (196, N'Abc Fagbokhandel AS, Pilestredet 41B, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (197, N'Lille Arkana, Youngstorget 6, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (198, N'Ruuds Antikvariat, Ullevålsveien 35, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (199, N'Chrom AS, Karoline Kristiansens vei 3, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (200, N'Halvbroren Bookstore, Akersgata 47/49, Oslo')
GO
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (201, N'Bokstua educational forum, Sofies plass 3, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (202, N'Barnas Egen Bokverden, Akersgata 47, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (203, N'Lunde publishing AS, Sinsenveien 25, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (204, N'Outland Storgata, Storgata 26, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (205, N'Cappelens Forslag bookshop, Bernt Ankers gate 4B, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (206, N'Nordea, Torggata 72, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (207, N'Storhamarsenteret, Måsåbekkvegen 2, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (208, N'SpareBank 1 Østlandet, Måsåbekkvegen 2, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (209, N'Jernbanepersonalets bank og forsikring avdeling Hamar, Stangevegen 12, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (210, N'Totens Sparebank, Parkgata 85, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (211, N'SpareBanken Hedmark, Parkgata 2, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (212, N'Handelsbanken Hamar, Finanshuset, Torggata 72, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (213, N'SpareBank 1 Østlandet, Torggata 12-14, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (214, N'DNB Hamar, Vangsvegen 70, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (215, N'SPAR Ottestad, Hobergvegen 147, Ottestad')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (216, N'Nimo klinikken, Øvre Storgate 4-6, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (217, N'Ambulansetjenesten Vestre Viken HF, Bergstien 24, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (218, N'Hamborgstrøm helse- og omsorgsdistrikt, Øvre Storgate 96, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (219, N'Drammen hospital, Dronninggata 28, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (220, N'Drammen Psychiatric Center (DPS), Øvre Strandgate 2, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (221, N'Blå Kors Borgestadklinikken Bragernes, Cappelens gate 42, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (222, N'Aleris Sykehus Drammen, Albums gate 9, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (223, N'Benh Vien, Bonnevies gate 4, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (224, N'Brystdiagnostisk senter, Vestre Viken, Dronninggata 28, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (225, N'Habilitetetssenteret, Wergelands gate 10T, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (226, N'KORPEVEIEN PRIVATKLINIKK, Havnegata 10, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (227, N'Landfalløya Medical Offices, Landfalløya 49, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (228, N'Fredholt sykehjem, Gamleveien 9, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (229, N'Bessungen økologiske kulturbarnehage, Buskerudveien 142, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (230, N'Fløibanen, Vetrlidsallmenningen 21, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (231, N'Bergen stasjon, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (232, N'BrimiBue, Sognefjellsvegen 13')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (233, N'Amore Lom AS, Sognefjellsvegen 1, Lom')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (234, N'Dronningens Gate D2, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (235, N'Trondheim Sentralstasjon, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (236, N'Hurtigbåtterminalen, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (237, N'Marienborg Stasjon, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (238, N'Bratsbergvegen, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (239, N'Strindheim (K), Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (240, N'Postterminalen, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (241, N'Postterminalen, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (242, N'REMA 1000 Torggata, Torggata 2, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (243, N'Europris Bryn, Tvetenveien 55, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (244, N'KIWI Parkveien, Parkveien 8, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (245, N'Coop Mega Alexander Kiellands Plass, Waldemar Thranes gate 72, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (246, N'MENY Oslo City, Stenersgata 1, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (247, N'MENY Bjølsen, Moldegata 1, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (248, N'REMA 1000 Fyrstikktorget, Karoline Kristiansens vei 2, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (249, N'KIWI Bislett, Thereses gate 30c, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (250, N'Ranthai Kanya Areeya Gjellum, Trondheimsveien 157, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (251, N'KIWI, Dronning Eufemias gate 38, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (252, N'REMA 1000 Vulkan, Maridalsveien 15, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (253, N'REMA 1000 Sørenga, Sørengkaia 11, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (254, N'REMA 1000 Rodeløkka, Trondheimsveien 72, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (255, N'REMA 1000 Parkveien, Parkveien 21, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (256, N'REMA 1000 Sannergata, Sannergata 3, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (257, N'REMA 1000 Vika, Parkveien 64, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (258, N'KIWI Niels Juelsgate, Frognerveien 9B, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (259, N'KIWI Briskeby, Løvenskiolds gate 26, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (260, N'REMA 1000 Hovin, Hovinveien 43, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (261, N'Ran Thai, Trondheimsveien 157, Oslo')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (262, N'Nordea -Kun avtalte møter, Brannvaktsgate 19, Larvik')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (263, N'SpareBank 1 BV, Fritzøe Brygge 1, Larvik')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (264, N'Danske Bank Larvik, Elveveien 34, Larvik')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (265, N'Handelsbanken Larvik, Fritzøe Brygge 1, Larvik')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (266, N'Western Union Bank, Lilletorget 1, Larvik')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (267, N'Larvikbanken - din personlige sparebank, Sigurds gate 1, Larvik')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (268, N'DNB Larvik, Sanden 1, Larvik')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (269, N'M3 Helse AS, Storhamargata 34, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (270, N'Torggata medical center, Torggata 71, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (271, N'Stortorget Medical Center, Torggata 83, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (272, N'?????????????????????????????????????????Sykehuset Innlandet - fysikalsk medisin og rehabilitering, ?Jørgen Jensens veg 7, Ottestad')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (273, N'"Raskere Tilbake" poliklinikk Avd.Ottestad, Søster Borghilds veg 7-9, Ottestad')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (274, N'Hospital inland Hamar, Skolegata 32, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (275, N'Sanderud sykehus, Vangsvegen, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (276, N'Drammen, Strømsø Torg 1, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (277, N'Torget Vest, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (278, N'Drammen busstasjon, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (279, N'Bangeløkka, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (280, N'Postterminalen, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (281, N'Comfort Hotel Holberg, Strandgaten 190, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (282, N'Clarion Hotel Admiral, C. Sundts gate 9, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (283, N'Scandic Neptun, Valkendorfsgaten 8, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (284, N'Hotel Park Bergen, Harald Hårfagres gate 35, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (285, N'First Hotel Bergen Marin, Rosenkrantzgaten 8, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (286, N'Hotel No13, Torgallmenningen 13, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (287, N'Naboen Pub & Restaurant, Sigurds gate 4, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (288, N'Spisekroken, Klostergaten 8, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (289, N'Bryggeloftet & Stuene Restaurant, Bryggen 11, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (290, N'Potetkjelleren Restaurant, Kong Oscars gate 1A, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (291, N'Egon, Vetrlidsallmenningen 2, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (292, N'Marg & Bein, Fosswinckels gate 18, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (293, N'Café Opera, Engen 18, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (294, N'Egon, Torgallmenningen 11, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (295, N'Fløien Folkerestaurant, Fløyfjellet 2, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (296, N'Sumo Restaurant Bergen Sentrum, Vestre Torggaten 3, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (297, N'Ichiban Sushi, Håkonsgaten 17, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (298, N'Ma Ma Thai, Kaigaten 20, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (299, N'Alléhjørnet Thai, Herman Foss'' gate 12, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (300, N'Victoria Cafe & Pub, Kong Oscars gate 29, Bergen')
GO
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (301, N'Trondheim Sentralstasjon, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (302, N'Skansen stasjon, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (303, N'Lademoen, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (304, N'Rotvoll, Arkitekt Ebbells veg, Ranheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (305, N'Marienborg, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (306, N'Lerkendal, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (307, N'Lilleby stasjon, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (308, N'Leangen stasjon, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (309, N'Kyvatnet, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (310, N'Munkvoll, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (311, N'Selsbakk stasjon, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (312, N'Hamar stasjon, Strandgata 2, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (313, N'Hamar skysstasjon, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (314, N'Strandvegen/Vognvegen, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (315, N'Breidablikk, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (316, N'Hjellum, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (317, N'Coop Ottadalen BA, Gnr 39 Bnr 1, Lom')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (318, N'Europris Lom, Stupulvegen 11')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (319, N'Akademika BI Bergen, Kong Christian Frederiks plass 3, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (320, N'Akademika HVL, Inndalsveien 28, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (321, N'Sprell Bergen Sentrum, Christian Michelsens gate 5, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (322, N'Norli, Galleriet, Torgallmenningen 8, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (323, N'ARK Xhibition Bergen, Småstrandgaten 3, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (324, N'ARK Beyer, Strandgaten 4, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (325, N'Akademika Studentsenteret, Parkveien 1, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (326, N'Akademika AS Hovedkontor, Kanalveien 51, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (327, N'Akademika NHH, Helleveien 30, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (328, N'Platekompaniet - Torgallmenningen, Torgallmenningen 5, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (329, N'Litteraturhuset i Bergen, Østre Skostredet 5, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (330, N'Witchy Bitchy Beauty Spot & Original Import, Nikolaikirkeallmenningen 4, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (331, N'Outland Bergen, Fortunen 4, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (332, N'ARK Oasen Senter Bergen, Folke Bernadottes vei 52, Fyllingsdalen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (333, N'Harald Mikkelsen Anubis Antikvariat, Kong Oscars gate 43, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (334, N'Norli, Strandgaten 1, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (335, N'Bergen Kristne Bokhandel AS, Øvre Korskirkeallmenningen 6, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (336, N'Norli, Storsenter, Strømgaten 8, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (337, N'Norli, Kringsjåveien 83-85, Laksevåg')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (338, N'Anna Forlag, Breiviken 6, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (339, N'Drammen, Strømsø Torg 1, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (340, N'Brakerøya, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (341, N'Gulskogen, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (342, N'Klinikk Adine, Nansetgata 66, Larvik')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (343, N'Torget Medisinske Senter, Torget 1, Larvik')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (344, N'Sentrum Legekontor, Sigurds gate 4, Larvik')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (345, N'Sykehuset Vestfold HF avdeling Larvik, Greveveien 16, Larvik')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (346, N'Larvik Casualty, Greveveien 16, Larvik')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (347, N'DPS Vestfold, Kristian Fredriks vei 10, Larvik')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (348, N'Rekkevik sykehjem, Rekkeviks gate 51, Larvik')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (349, N'Quality Hotel Augustin, Kongens gate 26, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (350, N'Britannia Hotel, Dronningens gate 5, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (351, N'Clarion Hotel Trondheim, Brattørkaia 1, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (352, N'Sushi Bar, Munkegata 39, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (353, N'Szechuan Restaurant, Olav Tryggvasons Gate 20, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (354, N'Egon Tårnet, Otto Nielsens veg 4, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (355, N'Frati restaurant, Kongens gate 20, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (356, N'Sushime, Beddingen 1, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (357, N'Emilies Eld Restaurant & Bar, Kongens gate 30, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (358, N'Trondhjem Mikrobryggeri, Prinsens Gate 39, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (359, N'Kyoto Restaurant, Dronningens gate 26, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (360, N'Baklandet Skydsstation, Øvre Bakklandet 33, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (361, N'Jonathan Grill, Dronningens gate 5, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (362, N'Graffi Grill og Bar Midtbyen, Olav Tryggvasons Gate 24, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (363, N'Krambua Trondheim, Krambugata 12, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (364, N'Banksalen Restaurant, Kongens gate 4, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (365, N'Sabrura Sticks & Sushi, Byhaven, Olav Tryggvasons Gate 28, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (366, N'Frida, Fjordgata 15, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (367, N'Benja Siam A/S, Ravelsveita 6, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (368, N'Café Løkka, Dokkgata 8, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (369, N'Hamar stasjon, Strandgata 2, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (370, N'Outland Trondheim, Jomfrugata 4, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (371, N'Ark Bookstore, Tinghusplassen 1, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (372, N'Akademika, Alfred Getz'' vei 3, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (373, N'ARK, Trondheim Torg, Tinghusplassen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (374, N'ARK Brunhjørnet Trondheim, Kongens gate 10, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (375, N'Nomaden, Thomas Angells gate 19, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (376, N'SELLANRAA Bok & Bar, Kongens gate 2, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (377, N'Akademika Øya, Mauritz Hansens gate 2, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (378, N'ARK Sirkus Shopping Trondheim, Falkenborgvegen 9, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (379, N'ARK Valentinlyst Center Trondheim, Anders Estenstads veg 2-22, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (380, N'Akademika DMMH, Thrond Nergaards veg 17, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (381, N'Norli, City Lade, Håkon 7. gt 9, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (382, N'ARK City Lade Trondheim, Haakon VIIs gate 9, Sør-Trønderlang')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (383, N'Akademika, Tungasletta 2, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (384, N'Akademika Dragvoll, Universitetssenteret Dragvoll Bygg 7, Nivå 3, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (385, N'Platekompaniet, Munkegata 31, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (386, N'Ark Bruns Brunhjørnet, Kongens gate 10, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (387, N'Akademika, Gunnerus gate 1, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (388, N'Wangsmo Antikvariat AS, Vår Frue Strete 1, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (389, N'Notabene Byhaven, BYHAVEN, Olav Tryggvasons Gate 28, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (390, N'Comfort Hotel Union Brygge, Grønland 64, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (391, N'Laythai Restaurant, Griffenfelds gate 3, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (392, N'Mr Pizza Drammen, Sankt Olavs gate 4, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (393, N'Pizzabakeren Åssiden, Vårveien 20, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (394, N'NamNam Lier, Lierstranda 139, Lier')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (395, N'Zemi AS, Grønland 38B, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (396, N'Restaurant Costa, Torgeir Vraas Plass 1, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (397, N'Håndverkeren selskapslokaler AS, Nedre Storgate 13, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (398, N'Liang Juan Kro, Professor Smiths alle 58, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (399, N'Matendo kultursenter, Grønland 60, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (400, N'Ask & Loke spiseri og bar, Øvre Torggate 4, Drammen')
GO
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (401, N'Vertshuset Oscar & Stallen, Øvre Torggate 6, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (402, N'O''Learys, Amtmand Bloms gate 2, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (403, N'Yaya''s Drammen, Engene 6, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (404, N'McDonald''s, Schwenckegata 1, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (405, N'Pizzabakeren Bragernes, Rådhusgata 35, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (406, N'Peppes Pizza - Drammen Stasjon, Drammen Stasjon, Strømsø Torg 1, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (407, N'Subway Strømsø Torg, Strømsø Torg 5A, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (408, N'Taki Pizza og Grill, Tollbugata 1, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (409, N'Frukt & Grønt, Tollbugata 6, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (410, N'REMA 1000 Kløverhuset, Strandgaten 13, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (411, N'REMA 1000, Nedre Korskirkeallmenningen 1A, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (412, N'REMA 1000 Lars Hilles gate, Lars Hilles gate 19, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (413, N'REMA 1000 Dreggen, Dreggsallmenningen 10-12, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (414, N'REMA 1000 Tollboden, C. Sundts gate 60, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (415, N'REMA 1000 Viken, Damsgårdsveien 35-37, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (416, N'REMA 1000, Øvre Fyllingsveien 77, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (417, N'REMA 1000 Minde, Kanalveien 5, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (418, N'REMA 1000 Lynghaugparken, Dag Hammarskjolds vei 1, Fyllingsdalen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (419, N'REMA 1000 Landås, Nattlandsveien 84, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (420, N'REMA 1000 Nygårdsgaten, Nygårdsgaten 17-19, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (421, N'MENY Bergen Storsenter, Bergen Storsenter, Strømgaten 8, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (422, N'REMA 1000 Wergeland, Fageråsveien 2, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (423, N'REMA 1000 Spectrum, Folke Bernadottes vei 44, Fyllingsdalen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (424, N'KIWI Birkebeiner Center, Nye Sandviksveien 9, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (425, N'REMA 1000, Jon Smørs gate 11, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (426, N'SPAR Karensfryd, Frydenbølien 17, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (427, N'Life, Torgallmenningen 8, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (428, N'REMA 1000 Danmarksplass, Fjøsangerveien 32C, Bergen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (429, N'REMA 1000 Nygård, Gravdalsveien 4, Laksevåg')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (430, N'Larvik sentrumsterminal, Larvik')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (431, N'Larvik sentrumsterminal, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (432, N'Jordfall, Norway')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (433, N'Larvik stasjon, Larvik')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (434, N'Scandic Hamar, Vangsvegen 121, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (435, N'Clarion Collection Hotel Astoria, Torggata 23, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (436, N'Scandic Ringsaker, Kårtorpvegen 1, Furnes')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (437, N'First Hotel Victoria, Strandgata 21, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (438, N'Pizzanini Hamar, Torggata 24, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (439, N'Royal India, Strandgata 37, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (440, N'The Irishman AS, Strandgata 31, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (441, N'Hellas Hamar AS, Torggata 83, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (442, N'Viking Kebab og Pizza, Strandgata 55, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (443, N'Nordre Sving Serveringsdrift, Vikingskipet, Åkersvikvegen 1, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (444, N'Iskroa, Kornsilovegen 54, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (445, N'Basarene, Storhamargata 2, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (446, N'Café Valuta, Torggata 100, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (447, N'Big Horn Hamar, Torggata 82, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (448, N'McDonald''s Hamar, Torggata 81/83, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (449, N'Stortorvet Gjestgiveri Hamar, Kirkegata 3, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (450, N'Hamar Asia Mat, Grønnegata 72, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (451, N'O''Leary''s, Strandgata 21, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (452, N'Nagomi, Strandgata 21, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (453, N'Fermate, Grønnegata 21, Hamar')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (454, N'ARK Torget Vest Drammen, Rådhusgata 2, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (455, N'ARK Strømsø senter Drammen, Bjørnstjerne Bjørnsons gate 60, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (456, N'ARK Gulskogen Drammen, Guldlisten 35, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (457, N'Notabene Konnerud, Pettersvollen 3, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (458, N'Norli CC-Varehus, CC Drammen, Tomtegata 36, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (459, N'Norli Papirbredden, Grønland 58, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (460, N'Norli, Magasinet Drammen Kjøpesenter, Nedre Storgate 2, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (461, N'Norli, Grønland 58, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (462, N'Norli, Guldlisten 35, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (463, N'Letter and Image AS, Skabos gate 15, Drammen')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (464, N'Coop Obs, Haakon VIIs gate 9, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (465, N'Coop Midt-Norge SA, City lade, Haakon VIIs gate 9, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (466, N'REMA 1000 Elgeseter, Klæbuveien 68, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (467, N'REMA 1000 Ilsvika, Mellomila 75, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (468, N'MENY Sverresborg, Gamle Oslovei 1, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (469, N'Rema 1000, John Skaarvolds veg 40, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (470, N'MENY Moholt, Vegamot 8, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (471, N'Europris Lade, Haakon VIIs gate 25B, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (472, N'REMA 1000 Olav Tryggvasonsgate, Olav Tryggvasons Gate 15, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (473, N'Bunnpris Moholt, Bregnevegen 67, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (474, N'REMA 1000 Torvet, Munkegata 22, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (475, N'MENY, Beddingen 12, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (476, N'Rema 1000, Fjellseterveien 1, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (477, N'REMA 1000 Moholt, Brøsetvegen 177, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (478, N'Rema 1000, Stadsing Dahls gate 5, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (479, N'REMA 1000 Prinsensgate, Prinsens Gate 49, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (480, N'Bunnpris Nidarvoll, Baard Iversens veg 2, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (481, N'Rema 1000, Rosenborg gate 1-3, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (482, N'Coop Mega Nardo, Hans Baucks veg 1, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (483, N'REMA 1000 Bromstad, Kong Øysteins veg 7, Trondheim')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (484, N'Quality Hotel Grand Farris, Storgata 38')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (485, N'Skotta Bryggeresturang, Kirkestredet 11, Larvik')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (486, N'McDonald''s Nordbyen Storsenter, Yttersøveien 2, Larvik')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (487, N'Glassmestern Bar og lunch, Torget 2, Larvik')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (488, N'Bøkekroa, Gunnar Thoresens Vei 4, Larvik')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (489, N'New Ambassador Restaurant, Torget 2, Larvik')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (490, N'Il Passatore Art Restaurant, Torget 6, Larvik')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (491, N'China City, Prinsegata 13, Larvik')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (492, N'Pica Pica, Strandpromenaden 49, Larvik')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (493, N'Domino''s Pizza, Nansetgata 36, Larvik')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (494, N'Bedehuset, Herregårdsbakken 1, Larvik')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (495, N'Subway Nansetgata, Nansetgata 105A, Larvik')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (496, N'Din Sushi Larvik, Yttersøveien 2, Larvik')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (497, N'Stallen Restaurant, Kaupangveien, Larvik')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (498, N'Pizzabakeren Larvik, Kongegata 33, Larvik')
INSERT [dbo].[lookupAddresstable] ([AddressID], [placeName]) VALUES (499, N'Spiseriet Indisk Tandori, Storgata 24, Larvik')
GO
